//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1,2,3,5,8,13,21,34,55,89,…
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <stdio.h>
#include <stdlib.h>

int fib(int n)
{
	if (n <= 1)
	{
		return 1;
	}
	else
	{
		return fib(n-1) + fib(n-2);
	}
}

long long solution(int limit)
{
	long long *listn = malloc(limit * sizeof(long long));
	int count = 0;

	for (int i = 0; fib(i) <= limit; i++)
	{
		if (fib(i) % 2 == 0)
		{
			listn[count] = fib(i);
			count++;
		}
	}

	long long sum = 0;
	for (int i = 0; i < count; i++)
	{
		sum += listn[i];
	}
	return sum;
}


int main(int argc, char **argv)
{
	long long answer = solution(4000000);
	printf("%lld\n", answer);

}
